CMakeLists.txt: use pkg-config to detect openssl when possible
In order to take into account the libraries used by openssl when
building statically, using pkg-config is recommended. This patch
therefore improves the CMakeLists.txt to use pkg-config to detect
openssl when pkg-config is available. This will avoid the following
static build failure when openssl needs to link with -latomic:

/home/autobuild/autobuild/instance-13/output-1/host/lib/gcc/sparc-buildroot-linux-uclibc/10.4.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: /home/autobuild/autobuild/instance-13/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libssl.a(ssl_cert.o): in function `ssl_cert_free':
ssl_cert.c:(.text+0x384): undefined reference to `__atomic_fetch_sub_4'

Fixes:
 - http://autobuild.buildroot.org/results/417c86963ffe038aa052ea3cf19fd52c3e9b7396

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>